const Constants = Object.freeze({
MAX_POWER: 0.175,
MAX_REVERSE: 0.155,
POWER_FACTOR: 0.004,
REVERSE_FACTOR: 0.003,

DRAG: 0.95,
ANGULAR_DRAG: 0.95,
TURN_SPEED: 0.002,


// PLAYER
	PLAYER_WIDTH: 50,
	PLAYER_HEIGHT: 75,
	PLAYER_MAX_HP: 100,

// MAP
	MAP_SIZE: 3000,
	TILE_WIDTH: 50,
	TILE_HEIGHT: 50,

// MATCHMAKING
	MAX_PLAYERS_ALLOWED: 10,

// PROJECTILE
	PROJECTILE_RADIUS: 20,
	PROJECTILE_DAMAGE: 34,
// COLLECTIBLES
	COLLECTIBLES_SPAWN_RATE: 15, //in seconds
	LIST_OF_COLLECTIBLES: [2, 3],
		// SPEED BOOST
		SPEED_BOOST_TYPE: 2,
		SPEED_BOOST_TIME: 30, //in seconds
		SPEED_BOOST_DURATION: 20, //in seconds
		// TRIPLE SHOT
		TRIPLE_SHOT_TYPE: 3,
		TRIPLE_SHOT_TIME: 30,
		TRIPLE_SHOT_DURATION: 10,
		TRIPLE_SHOT_ANGLE: 0.2,
		// HEALTH REGEN
		HEALTH_REGEN_TYPE: 4,
		HEALTH_REGEN_TIME: 30,

});
if (typeof window === 'undefined') {
	module.exports = Constants;
} else {
	window.Constants = Constants;
}
